subprojects {
    plugins.withId("com.android.base") {
        android {
            compileSdk = 37
            ndkVersion = "28.2.13676358"
            
            defaultConfig {
                minSdk = 24
                targetSdk = 37
            }
            
            compileOptions {
                sourceCompatibility = JavaVersion.VERSION_21
                targetCompatibility = JavaVersion.VERSION_21
            }
        }
    }
}

apply from: 'api/manifest.gradle'

ext {
    versionCode = (findProperty("versionCode") ?: "101000").toString().toInteger()
    versionName = (findProperty("versionName") ?: "1.1").toString()
}
