plugins {
    id('com.android.application')
    id('org.jetbrains.kotlin.plugin.compose')
}

android {
    namespace 'com.stellar.demo'

    defaultConfig {
        applicationId "com.stellar.api.demo"
        versionCode 1
        versionName "1.0.0"
    }

    buildFeatures {
        buildConfig true
        compose true
        aidl true
    }

    signingConfigs {
        sign
    }

    buildTypes {
        debug {
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
        }
    }
}

dependencies {
    implementation project(':api')
    implementation project(':provider')
    implementation project(':aidl')
    implementation project(':shared')
    implementation project(':userservice')

    implementation demoLibs.bundles.coroutines

    implementation demoLibs.bundles.base

    implementation demoLibs.material

    def composeBom = platform(demoLibs.composeBom)
    implementation composeBom
    implementation demoLibs.bundles.compose
    debugImplementation demoLibs.composeUiTooling

    implementation demoLibs.capsule
}

