plugins {
    id 'com.android.library'
}

android {
    namespace 'roro.stellar.shizuku'
    buildFeatures {
        buildConfig false
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    api project(':shizuku-aidl')

    implementation serverLibs.androidxAnnotation
}
